
CREATE TABLE USUARIO (
    USUARIO_ID SERIAL NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    TIPO INTEGER NOT NULL, -- 1. ADMIN; 2. CLIENTE, 3. FORNECEDOR
    CONSTRAINT USUARIO_PK PRIMARY KEY (USUARIO_ID),
    CONSTRAINT USUARIO_TIPO_CK CHECK (TIPO IN (1, 2, 3))
);

CREATE TABLE ENDERECO (
    ENDERECO_ID SERIAL NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
    RUA VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(255) NOT NULL,
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255) NOT NULL,
    CEP VARCHAR(255) NOT NULL,
    CONSTRAINT ENDERECO_PK PRIMARY KEY (ENDERECO_ID)
);
CREATE TABLE CLIENTE (
    CLIENTE_ID SERIAL NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    ENDERECO_ID INTEGER NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    CARTAO_CREDITO VARCHAR(100) NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT CLIENTE_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID),
    CONSTRAINT CLIENTE_ENDERECO_ID_FK FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ENDERECO_ID)
);

CREATE TABLE FORNECEDOR (
    FORNECEDOR_ID SERIAL NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    ENDERECO_ID INTEGER NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(100) NOT NULL,
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (FORNECEDOR_ID),
    CONSTRAINT FORNECEDOR_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID),
    CONSTRAINT FORNECEDOR_ENDERECO_ID_FK FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ENDERECO_ID)
);

CREATE TABLE ADMINISTRADOR (
    ADMINISTRADOR_ID SERIAL NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CONSTRAINT ADMINISTRADOR_PK PRIMARY KEY (ADMINISTRADOR_ID),
    CONSTRAINT ADMINISTRADOR_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID)
);

CREATE TABLE PRODUTO (
    PRODUTO_ID SERIAL NOT NULL,
    FORNECEDOR_ID INTEGER NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    FOTO BYTEA NULL,
    CONSTRAINT PRODUTO_PK PRIMARY KEY (PRODUTO_ID),
    CONSTRAINT PRODUTO_FORNECEDOR_ID_FK FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (FORNECEDOR_ID)
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID SERIAL NOT NULL,
    PRODUTO_ID INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    PRECO FLOAT NOT NULL,
    CONSTRAINT ESTOQUE_PK PRIMARY KEY (ESTOQUE_ID),
    CONSTRAINT ESTOQUE_PRODUTO_ID_FK FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (PRODUTO_ID),
    CONSTRAINT ESTOQUE_QUANTIDADE_CK CHECK (QUANTIDADE >= 0),
    CONSTRAINT ESTOQUE_PRECO_CK CHECK (PRECO >= 0)
);

CREATE TABLE PEDIDO_SITUACAO (
    PEDIDO_SITUACAO_ID SERIAL NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    CONSTRAINT PEDIDO_SITUACAO_PK PRIMARY KEY (PEDIDO_SITUACAO_ID)
);

CREATE TABLE PEDIDO (
    PEDIDO_ID SERIAL NOT NULL,
    CLIENTE_ID INTEGER NOT NULL,
    PEDIDO_NUMERO INTEGER NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    DATA_ENTREGA DATE NULL,
    DATA_CANCELAMENTO DATE NULL,
    SITUACAO_ID INTEGER NOT NULL,
    CONSTRAINT PEDIDO_PK PRIMARY KEY (PEDIDO_ID),
    CONSTRAINT PEDIDO_NUMERO_UK UNIQUE (PEDIDO_NUMERO),
    CONSTRAINT PEDIDO_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID),
    CONSTRAINT PEDIDO_SITUACAO_ID_FK FOREIGN KEY (SITUACAO_ID) REFERENCES PEDIDO_SITUACAO (PEDIDO_SITUACAO_ID)
);

CREATE TABLE ITEM_PEDIDO (
    ITEM_PEDIDO_ID SERIAL NOT NULL,
    PEDIDO_ID INTEGER NOT NULL,
    PRODUTO_ID INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    PRECO FLOAT NOT NULL,
    CONSTRAINT ITEM_PEDIDO_PK PRIMARY KEY (ITEM_PEDIDO_ID),
    CONSTRAINT ITEM_PEDIDO_PEDIDO_ID_FK FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO (PEDIDO_ID),
    CONSTRAINT ITEM_PEDIDO_PRODUTO_ID_FK FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (PRODUTO_ID),
    CONSTRAINT ITEM_PEDIDO_QUANTIDADE_CK CHECK (QUANTIDADE > 0),
    CONSTRAINT ITEM_PEDIDO_PRECO_CK CHECK (PRECO >= 0)
);

INSERT INTO PEDIDO_SITUACAO (DESCRICAO) VALUES ('NOVO');
INSERT INTO PEDIDO_SITUACAO (DESCRICAO) VALUES ('ENTREGUE');
INSERT INTO PEDIDO_SITUACAO (DESCRICAO) VALUES ('CANCELADO');

-- Senha do admin: "123" (hash bcrypt compatível com password_verify do PHP)
INSERT INTO USUARIO (EMAIL, SENHA, TIPO)
VALUES ('admin@lojaweb.com', '$2b$10$0Yx/xGqjAy6MBM8XRn.yUucPQTZoF9ghffZz9yEY/vbvthiLb4nSm', 1);

INSERT INTO ADMINISTRADOR (USUARIO_ID, NOME) 
VALUES (1, 'admin');
